version: "3"

networks:
  kpo:
    external: true

services:
  argareeva:
    image: postgres:latest
    network_mode: bridge
    volumes:
      - ./argareeva/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gareeva0223
      POSTGRES_DB: argareeva
      APP_DB_USER: docker
      APP_DB_PASS: docker
    healthcheck:
      test: PGPASSWORD='gareeva0223' psql -U postgres --command='SELECT 1' --dbname=argareeva
      interval: 1s
      timeout: 2s
      retries: 5
    # networks:
    #   - kpo
  # authorize:
  #   build: ./authorize/
  #   network_mode: bridge
  #   ports:
  #     - "5137:5137"
  #   environment:
  #     - DB_URL=postgresql://root:root@db/db?sslmode=disable
  #     - PORT=8003
  #   restart: on-failure
  #   depends_on:
  #     argareeva:
  #       condition: service_healthy